// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.1
// source: proto/authorization/authorization.proto

package authorization

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetTokenRequest is empty - certificate comes from mTLS context.
type GetTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenRequest) Reset() {
	*x = GetTokenRequest{}
	mi := &file_proto_authorization_authorization_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenRequest) ProtoMessage() {}

func (x *GetTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authorization_authorization_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenRequest.ProtoReflect.Descriptor instead.
func (*GetTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_authorization_authorization_proto_rawDescGZIP(), []int{0}
}

// GetTokenResponse contains the issued token and expiration.
type GetTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenResponse) Reset() {
	*x = GetTokenResponse{}
	mi := &file_proto_authorization_authorization_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenResponse) ProtoMessage() {}

func (x *GetTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authorization_authorization_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenResponse.ProtoReflect.Descriptor instead.
func (*GetTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_authorization_authorization_proto_rawDescGZIP(), []int{1}
}

func (x *GetTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GetTokenResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

// RegisterGuardRequest defines a guard for a capability.
type RegisterGuardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuardId       string                 `protobuf:"bytes,1,opt,name=guard_id,json=guardId,proto3" json:"guard_id,omitempty"` // e.g. "vicky.storage.write"
	Permissions   []string               `protobuf:"bytes,2,rep,name=permissions,proto3" json:"permissions,omitempty"`        // Required permissions
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterGuardRequest) Reset() {
	*x = RegisterGuardRequest{}
	mi := &file_proto_authorization_authorization_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterGuardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterGuardRequest) ProtoMessage() {}

func (x *RegisterGuardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authorization_authorization_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterGuardRequest.ProtoReflect.Descriptor instead.
func (*RegisterGuardRequest) Descriptor() ([]byte, []int) {
	return file_proto_authorization_authorization_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterGuardRequest) GetGuardId() string {
	if x != nil {
		return x.GuardId
	}
	return ""
}

func (x *RegisterGuardRequest) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

// RegisterGuardResponse is empty on success; errors use gRPC status.
type RegisterGuardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterGuardResponse) Reset() {
	*x = RegisterGuardResponse{}
	mi := &file_proto_authorization_authorization_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterGuardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterGuardResponse) ProtoMessage() {}

func (x *RegisterGuardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authorization_authorization_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterGuardResponse.ProtoReflect.Descriptor instead.
func (*RegisterGuardResponse) Descriptor() ([]byte, []int) {
	return file_proto_authorization_authorization_proto_rawDescGZIP(), []int{3}
}

// ValidateGuardRequest checks a token against a guard.
type ValidateGuardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuardId       string                 `protobuf:"bytes,1,opt,name=guard_id,json=guardId,proto3" json:"guard_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateGuardRequest) Reset() {
	*x = ValidateGuardRequest{}
	mi := &file_proto_authorization_authorization_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateGuardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateGuardRequest) ProtoMessage() {}

func (x *ValidateGuardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authorization_authorization_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateGuardRequest.ProtoReflect.Descriptor instead.
func (*ValidateGuardRequest) Descriptor() ([]byte, []int) {
	return file_proto_authorization_authorization_proto_rawDescGZIP(), []int{4}
}

func (x *ValidateGuardRequest) GetGuardId() string {
	if x != nil {
		return x.GuardId
	}
	return ""
}

func (x *ValidateGuardRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// ValidateGuardResponse indicates whether access is allowed.
type ValidateGuardResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Allowed            bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	MissingPermissions []string               `protobuf:"bytes,2,rep,name=missing_permissions,json=missingPermissions,proto3" json:"missing_permissions,omitempty"` // If denied, what's missing
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ValidateGuardResponse) Reset() {
	*x = ValidateGuardResponse{}
	mi := &file_proto_authorization_authorization_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateGuardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateGuardResponse) ProtoMessage() {}

func (x *ValidateGuardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authorization_authorization_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateGuardResponse.ProtoReflect.Descriptor instead.
func (*ValidateGuardResponse) Descriptor() ([]byte, []int) {
	return file_proto_authorization_authorization_proto_rawDescGZIP(), []int{5}
}

func (x *ValidateGuardResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *ValidateGuardResponse) GetMissingPermissions() []string {
	if x != nil {
		return x.MissingPermissions
	}
	return nil
}

// RevokeTokenRequest identifies the token to revoke.
type RevokeTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fingerprint   string                 `protobuf:"bytes,1,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"` // Certificate fingerprint
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeTokenRequest) Reset() {
	*x = RevokeTokenRequest{}
	mi := &file_proto_authorization_authorization_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTokenRequest) ProtoMessage() {}

func (x *RevokeTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authorization_authorization_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeTokenRequest.ProtoReflect.Descriptor instead.
func (*RevokeTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_authorization_authorization_proto_rawDescGZIP(), []int{6}
}

func (x *RevokeTokenRequest) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

// RevokeTokenResponse is empty on success; errors use gRPC status.
type RevokeTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeTokenResponse) Reset() {
	*x = RevokeTokenResponse{}
	mi := &file_proto_authorization_authorization_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTokenResponse) ProtoMessage() {}

func (x *RevokeTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authorization_authorization_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeTokenResponse.ProtoReflect.Descriptor instead.
func (*RevokeTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_authorization_authorization_proto_rawDescGZIP(), []int{7}
}

var File_proto_authorization_authorization_proto protoreflect.FileDescriptor

const file_proto_authorization_authorization_proto_rawDesc = "" +
	"\n" +
	"'proto/authorization/authorization.proto\x12\x16aegis.authorization.v1\"\x11\n" +
	"\x0fGetTokenRequest\"G\n" +
	"\x10GetTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\x03R\texpiresAt\"S\n" +
	"\x14RegisterGuardRequest\x12\x19\n" +
	"\bguard_id\x18\x01 \x01(\tR\aguardId\x12 \n" +
	"\vpermissions\x18\x02 \x03(\tR\vpermissions\"\x17\n" +
	"\x15RegisterGuardResponse\"G\n" +
	"\x14ValidateGuardRequest\x12\x19\n" +
	"\bguard_id\x18\x01 \x01(\tR\aguardId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"b\n" +
	"\x15ValidateGuardResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12/\n" +
	"\x13missing_permissions\x18\x02 \x03(\tR\x12missingPermissions\"6\n" +
	"\x12RevokeTokenRequest\x12 \n" +
	"\vfingerprint\x18\x01 \x01(\tR\vfingerprint\"\x15\n" +
	"\x13RevokeTokenResponse2\xb9\x03\n" +
	"\x14AuthorizationService\x12]\n" +
	"\bGetToken\x12'.aegis.authorization.v1.GetTokenRequest\x1a(.aegis.authorization.v1.GetTokenResponse\x12l\n" +
	"\rRegisterGuard\x12,.aegis.authorization.v1.RegisterGuardRequest\x1a-.aegis.authorization.v1.RegisterGuardResponse\x12l\n" +
	"\rValidateGuard\x12,.aegis.authorization.v1.ValidateGuardRequest\x1a-.aegis.authorization.v1.ValidateGuardResponse\x12f\n" +
	"\vRevokeToken\x12*.aegis.authorization.v1.RevokeTokenRequest\x1a+.aegis.authorization.v1.RevokeTokenResponseB.Z,github.com/zoobzio/aegis/proto/authorizationb\x06proto3"

var (
	file_proto_authorization_authorization_proto_rawDescOnce sync.Once
	file_proto_authorization_authorization_proto_rawDescData []byte
)

func file_proto_authorization_authorization_proto_rawDescGZIP() []byte {
	file_proto_authorization_authorization_proto_rawDescOnce.Do(func() {
		file_proto_authorization_authorization_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_authorization_authorization_proto_rawDesc), len(file_proto_authorization_authorization_proto_rawDesc)))
	})
	return file_proto_authorization_authorization_proto_rawDescData
}

var file_proto_authorization_authorization_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_authorization_authorization_proto_goTypes = []any{
	(*GetTokenRequest)(nil),       // 0: aegis.authorization.v1.GetTokenRequest
	(*GetTokenResponse)(nil),      // 1: aegis.authorization.v1.GetTokenResponse
	(*RegisterGuardRequest)(nil),  // 2: aegis.authorization.v1.RegisterGuardRequest
	(*RegisterGuardResponse)(nil), // 3: aegis.authorization.v1.RegisterGuardResponse
	(*ValidateGuardRequest)(nil),  // 4: aegis.authorization.v1.ValidateGuardRequest
	(*ValidateGuardResponse)(nil), // 5: aegis.authorization.v1.ValidateGuardResponse
	(*RevokeTokenRequest)(nil),    // 6: aegis.authorization.v1.RevokeTokenRequest
	(*RevokeTokenResponse)(nil),   // 7: aegis.authorization.v1.RevokeTokenResponse
}
var file_proto_authorization_authorization_proto_depIdxs = []int32{
	0, // 0: aegis.authorization.v1.AuthorizationService.GetToken:input_type -> aegis.authorization.v1.GetTokenRequest
	2, // 1: aegis.authorization.v1.AuthorizationService.RegisterGuard:input_type -> aegis.authorization.v1.RegisterGuardRequest
	4, // 2: aegis.authorization.v1.AuthorizationService.ValidateGuard:input_type -> aegis.authorization.v1.ValidateGuardRequest
	6, // 3: aegis.authorization.v1.AuthorizationService.RevokeToken:input_type -> aegis.authorization.v1.RevokeTokenRequest
	1, // 4: aegis.authorization.v1.AuthorizationService.GetToken:output_type -> aegis.authorization.v1.GetTokenResponse
	3, // 5: aegis.authorization.v1.AuthorizationService.RegisterGuard:output_type -> aegis.authorization.v1.RegisterGuardResponse
	5, // 6: aegis.authorization.v1.AuthorizationService.ValidateGuard:output_type -> aegis.authorization.v1.ValidateGuardResponse
	7, // 7: aegis.authorization.v1.AuthorizationService.RevokeToken:output_type -> aegis.authorization.v1.RevokeTokenResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_authorization_authorization_proto_init() }
func file_proto_authorization_authorization_proto_init() {
	if File_proto_authorization_authorization_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_authorization_authorization_proto_rawDesc), len(file_proto_authorization_authorization_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_authorization_authorization_proto_goTypes,
		DependencyIndexes: file_proto_authorization_authorization_proto_depIdxs,
		MessageInfos:      file_proto_authorization_authorization_proto_msgTypes,
	}.Build()
	File_proto_authorization_authorization_proto = out.File
	file_proto_authorization_authorization_proto_goTypes = nil
	file_proto_authorization_authorization_proto_depIdxs = nil
}
