// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.1
// source: proto/identity/identity.proto

package identity

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ValidateSessionRequest contains the session token to validate.
type ValidateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateSessionRequest) Reset() {
	*x = ValidateSessionRequest{}
	mi := &file_proto_identity_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateSessionRequest) ProtoMessage() {}

func (x *ValidateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_identity_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateSessionRequest.ProtoReflect.Descriptor instead.
func (*ValidateSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_identity_identity_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateSessionRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// ValidateSessionResponse contains validation result and user info if valid.
type ValidateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // Unix timestamp, 0 if invalid
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateSessionResponse) Reset() {
	*x = ValidateSessionResponse{}
	mi := &file_proto_identity_identity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateSessionResponse) ProtoMessage() {}

func (x *ValidateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_identity_identity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateSessionResponse.ProtoReflect.Descriptor instead.
func (*ValidateSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_identity_identity_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateSessionResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateSessionResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ValidateSessionResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

// GetUserRequest identifies a user by ID.
type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_proto_identity_identity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_identity_identity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_identity_identity_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// GetUserByEmailRequest identifies a user by email.
type GetUserByEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByEmailRequest) Reset() {
	*x = GetUserByEmailRequest{}
	mi := &file_proto_identity_identity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByEmailRequest) ProtoMessage() {}

func (x *GetUserByEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_identity_identity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByEmailRequest.ProtoReflect.Descriptor instead.
func (*GetUserByEmailRequest) Descriptor() ([]byte, []int) {
	return file_proto_identity_identity_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserByEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

// GetUserResponse contains user information.
// Email is not masked in mesh responses - masking is a boundary concern.
type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	EmailVerified bool                   `protobuf:"varint,5,opt,name=email_verified,json=emailVerified,proto3" json:"email_verified,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_proto_identity_identity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_identity_identity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_identity_identity_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetUserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetUserResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetUserResponse) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *GetUserResponse) GetEmailVerified() bool {
	if x != nil {
		return x.EmailVerified
	}
	return false
}

func (x *GetUserResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// ListProvidersRequest identifies the user whose providers to list.
type ListProvidersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProvidersRequest) Reset() {
	*x = ListProvidersRequest{}
	mi := &file_proto_identity_identity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProvidersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProvidersRequest) ProtoMessage() {}

func (x *ListProvidersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_identity_identity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProvidersRequest.ProtoReflect.Descriptor instead.
func (*ListProvidersRequest) Descriptor() ([]byte, []int) {
	return file_proto_identity_identity_proto_rawDescGZIP(), []int{5}
}

func (x *ListProvidersRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// ListProvidersResponse contains the user's linked OAuth providers.
type ListProvidersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Providers     []*Provider            `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProvidersResponse) Reset() {
	*x = ListProvidersResponse{}
	mi := &file_proto_identity_identity_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProvidersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProvidersResponse) ProtoMessage() {}

func (x *ListProvidersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_identity_identity_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProvidersResponse.ProtoReflect.Descriptor instead.
func (*ListProvidersResponse) Descriptor() ([]byte, []int) {
	return file_proto_identity_identity_proto_rawDescGZIP(), []int{6}
}

func (x *ListProvidersResponse) GetProviders() []*Provider {
	if x != nil {
		return x.Providers
	}
	return nil
}

// Provider represents a linked OAuth provider.
type Provider struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Type           string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`                                             // "github" or "google"
	ProviderUserId string                 `protobuf:"bytes,2,opt,name=provider_user_id,json=providerUserId,proto3" json:"provider_user_id,omitempty"` // External provider's user ID
	LinkedAt       int64                  `protobuf:"varint,3,opt,name=linked_at,json=linkedAt,proto3" json:"linked_at,omitempty"`                    // Unix timestamp
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Provider) Reset() {
	*x = Provider{}
	mi := &file_proto_identity_identity_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Provider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Provider) ProtoMessage() {}

func (x *Provider) ProtoReflect() protoreflect.Message {
	mi := &file_proto_identity_identity_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Provider.ProtoReflect.Descriptor instead.
func (*Provider) Descriptor() ([]byte, []int) {
	return file_proto_identity_identity_proto_rawDescGZIP(), []int{7}
}

func (x *Provider) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Provider) GetProviderUserId() string {
	if x != nil {
		return x.ProviderUserId
	}
	return ""
}

func (x *Provider) GetLinkedAt() int64 {
	if x != nil {
		return x.LinkedAt
	}
	return 0
}

// RevokeSessionRequest identifies the session to revoke.
type RevokeSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeSessionRequest) Reset() {
	*x = RevokeSessionRequest{}
	mi := &file_proto_identity_identity_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeSessionRequest) ProtoMessage() {}

func (x *RevokeSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_identity_identity_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeSessionRequest.ProtoReflect.Descriptor instead.
func (*RevokeSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_identity_identity_proto_rawDescGZIP(), []int{8}
}

func (x *RevokeSessionRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// RevokeSessionResponse is empty on success; errors use gRPC status.
type RevokeSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeSessionResponse) Reset() {
	*x = RevokeSessionResponse{}
	mi := &file_proto_identity_identity_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeSessionResponse) ProtoMessage() {}

func (x *RevokeSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_identity_identity_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeSessionResponse.ProtoReflect.Descriptor instead.
func (*RevokeSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_identity_identity_proto_rawDescGZIP(), []int{9}
}

// RevokeUserSessionsRequest identifies the user whose sessions to revoke.
type RevokeUserSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeUserSessionsRequest) Reset() {
	*x = RevokeUserSessionsRequest{}
	mi := &file_proto_identity_identity_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeUserSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeUserSessionsRequest) ProtoMessage() {}

func (x *RevokeUserSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_identity_identity_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeUserSessionsRequest.ProtoReflect.Descriptor instead.
func (*RevokeUserSessionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_identity_identity_proto_rawDescGZIP(), []int{10}
}

func (x *RevokeUserSessionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// RevokeUserSessionsResponse contains the count of revoked sessions.
type RevokeUserSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RevokedCount  uint32                 `protobuf:"varint,1,opt,name=revoked_count,json=revokedCount,proto3" json:"revoked_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeUserSessionsResponse) Reset() {
	*x = RevokeUserSessionsResponse{}
	mi := &file_proto_identity_identity_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeUserSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeUserSessionsResponse) ProtoMessage() {}

func (x *RevokeUserSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_identity_identity_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeUserSessionsResponse.ProtoReflect.Descriptor instead.
func (*RevokeUserSessionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_identity_identity_proto_rawDescGZIP(), []int{11}
}

func (x *RevokeUserSessionsResponse) GetRevokedCount() uint32 {
	if x != nil {
		return x.RevokedCount
	}
	return 0
}

// ListUserSessionsRequest identifies the user whose sessions to list.
type ListUserSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserSessionsRequest) Reset() {
	*x = ListUserSessionsRequest{}
	mi := &file_proto_identity_identity_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserSessionsRequest) ProtoMessage() {}

func (x *ListUserSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_identity_identity_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListUserSessionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_identity_identity_proto_rawDescGZIP(), []int{12}
}

func (x *ListUserSessionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// ListUserSessionsResponse contains the user's active sessions.
type ListUserSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*SessionInfo         `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserSessionsResponse) Reset() {
	*x = ListUserSessionsResponse{}
	mi := &file_proto_identity_identity_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserSessionsResponse) ProtoMessage() {}

func (x *ListUserSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_identity_identity_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListUserSessionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_identity_identity_proto_rawDescGZIP(), []int{13}
}

func (x *ListUserSessionsResponse) GetSessions() []*SessionInfo {
	if x != nil {
		return x.Sessions
	}
	return nil
}

// SessionInfo contains information about an active session.
type SessionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenPrefix   string                 `protobuf:"bytes,1,opt,name=token_prefix,json=tokenPrefix,proto3" json:"token_prefix,omitempty"` // First N chars for identification, not full token
	CreatedAt     int64                  `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`      // Unix timestamp
	ExpiresAt     int64                  `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`      // Unix timestamp
	UserAgent     string                 `protobuf:"bytes,4,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`       // Device/browser info
	IpAddress     string                 `protobuf:"bytes,5,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`       // Last known IP
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionInfo) Reset() {
	*x = SessionInfo{}
	mi := &file_proto_identity_identity_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInfo) ProtoMessage() {}

func (x *SessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_identity_identity_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInfo.ProtoReflect.Descriptor instead.
func (*SessionInfo) Descriptor() ([]byte, []int) {
	return file_proto_identity_identity_proto_rawDescGZIP(), []int{14}
}

func (x *SessionInfo) GetTokenPrefix() string {
	if x != nil {
		return x.TokenPrefix
	}
	return ""
}

func (x *SessionInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *SessionInfo) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *SessionInfo) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *SessionInfo) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

var File_proto_identity_identity_proto protoreflect.FileDescriptor

const file_proto_identity_identity_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/identity/identity.proto\x12\x11aegis.identity.v1\".\n" +
	"\x16ValidateSessionRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"g\n" +
	"\x17ValidateSessionResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x03R\texpiresAt\")\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"-\n" +
	"\x15GetUserByEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"\xb0\x01\n" +
	"\x0fGetUserResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tR\tavatarUrl\x12%\n" +
	"\x0eemail_verified\x18\x05 \x01(\bR\remailVerified\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\"/\n" +
	"\x14ListProvidersRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"R\n" +
	"\x15ListProvidersResponse\x129\n" +
	"\tproviders\x18\x01 \x03(\v2\x1b.aegis.identity.v1.ProviderR\tproviders\"e\n" +
	"\bProvider\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12(\n" +
	"\x10provider_user_id\x18\x02 \x01(\tR\x0eproviderUserId\x12\x1b\n" +
	"\tlinked_at\x18\x03 \x01(\x03R\blinkedAt\",\n" +
	"\x14RevokeSessionRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x17\n" +
	"\x15RevokeSessionResponse\"4\n" +
	"\x19RevokeUserSessionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"A\n" +
	"\x1aRevokeUserSessionsResponse\x12#\n" +
	"\rrevoked_count\x18\x01 \x01(\rR\frevokedCount\"2\n" +
	"\x17ListUserSessionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"V\n" +
	"\x18ListUserSessionsResponse\x12:\n" +
	"\bsessions\x18\x01 \x03(\v2\x1e.aegis.identity.v1.SessionInfoR\bsessions\"\xac\x01\n" +
	"\vSessionInfo\x12!\n" +
	"\ftoken_prefix\x18\x01 \x01(\tR\vtokenPrefix\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x03R\texpiresAt\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x04 \x01(\tR\tuserAgent\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x05 \x01(\tR\tipAddress2\xd5\x05\n" +
	"\x0fIdentityService\x12h\n" +
	"\x0fValidateSession\x12).aegis.identity.v1.ValidateSessionRequest\x1a*.aegis.identity.v1.ValidateSessionResponse\x12P\n" +
	"\aGetUser\x12!.aegis.identity.v1.GetUserRequest\x1a\".aegis.identity.v1.GetUserResponse\x12^\n" +
	"\x0eGetUserByEmail\x12(.aegis.identity.v1.GetUserByEmailRequest\x1a\".aegis.identity.v1.GetUserResponse\x12b\n" +
	"\rListProviders\x12'.aegis.identity.v1.ListProvidersRequest\x1a(.aegis.identity.v1.ListProvidersResponse\x12b\n" +
	"\rRevokeSession\x12'.aegis.identity.v1.RevokeSessionRequest\x1a(.aegis.identity.v1.RevokeSessionResponse\x12q\n" +
	"\x12RevokeUserSessions\x12,.aegis.identity.v1.RevokeUserSessionsRequest\x1a-.aegis.identity.v1.RevokeUserSessionsResponse\x12k\n" +
	"\x10ListUserSessions\x12*.aegis.identity.v1.ListUserSessionsRequest\x1a+.aegis.identity.v1.ListUserSessionsResponseB)Z'github.com/zoobzio/aegis/proto/identityb\x06proto3"

var (
	file_proto_identity_identity_proto_rawDescOnce sync.Once
	file_proto_identity_identity_proto_rawDescData []byte
)

func file_proto_identity_identity_proto_rawDescGZIP() []byte {
	file_proto_identity_identity_proto_rawDescOnce.Do(func() {
		file_proto_identity_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_identity_identity_proto_rawDesc), len(file_proto_identity_identity_proto_rawDesc)))
	})
	return file_proto_identity_identity_proto_rawDescData
}

var file_proto_identity_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_identity_identity_proto_goTypes = []any{
	(*ValidateSessionRequest)(nil),     // 0: aegis.identity.v1.ValidateSessionRequest
	(*ValidateSessionResponse)(nil),    // 1: aegis.identity.v1.ValidateSessionResponse
	(*GetUserRequest)(nil),             // 2: aegis.identity.v1.GetUserRequest
	(*GetUserByEmailRequest)(nil),      // 3: aegis.identity.v1.GetUserByEmailRequest
	(*GetUserResponse)(nil),            // 4: aegis.identity.v1.GetUserResponse
	(*ListProvidersRequest)(nil),       // 5: aegis.identity.v1.ListProvidersRequest
	(*ListProvidersResponse)(nil),      // 6: aegis.identity.v1.ListProvidersResponse
	(*Provider)(nil),                   // 7: aegis.identity.v1.Provider
	(*RevokeSessionRequest)(nil),       // 8: aegis.identity.v1.RevokeSessionRequest
	(*RevokeSessionResponse)(nil),      // 9: aegis.identity.v1.RevokeSessionResponse
	(*RevokeUserSessionsRequest)(nil),  // 10: aegis.identity.v1.RevokeUserSessionsRequest
	(*RevokeUserSessionsResponse)(nil), // 11: aegis.identity.v1.RevokeUserSessionsResponse
	(*ListUserSessionsRequest)(nil),    // 12: aegis.identity.v1.ListUserSessionsRequest
	(*ListUserSessionsResponse)(nil),   // 13: aegis.identity.v1.ListUserSessionsResponse
	(*SessionInfo)(nil),                // 14: aegis.identity.v1.SessionInfo
}
var file_proto_identity_identity_proto_depIdxs = []int32{
	7,  // 0: aegis.identity.v1.ListProvidersResponse.providers:type_name -> aegis.identity.v1.Provider
	14, // 1: aegis.identity.v1.ListUserSessionsResponse.sessions:type_name -> aegis.identity.v1.SessionInfo
	0,  // 2: aegis.identity.v1.IdentityService.ValidateSession:input_type -> aegis.identity.v1.ValidateSessionRequest
	2,  // 3: aegis.identity.v1.IdentityService.GetUser:input_type -> aegis.identity.v1.GetUserRequest
	3,  // 4: aegis.identity.v1.IdentityService.GetUserByEmail:input_type -> aegis.identity.v1.GetUserByEmailRequest
	5,  // 5: aegis.identity.v1.IdentityService.ListProviders:input_type -> aegis.identity.v1.ListProvidersRequest
	8,  // 6: aegis.identity.v1.IdentityService.RevokeSession:input_type -> aegis.identity.v1.RevokeSessionRequest
	10, // 7: aegis.identity.v1.IdentityService.RevokeUserSessions:input_type -> aegis.identity.v1.RevokeUserSessionsRequest
	12, // 8: aegis.identity.v1.IdentityService.ListUserSessions:input_type -> aegis.identity.v1.ListUserSessionsRequest
	1,  // 9: aegis.identity.v1.IdentityService.ValidateSession:output_type -> aegis.identity.v1.ValidateSessionResponse
	4,  // 10: aegis.identity.v1.IdentityService.GetUser:output_type -> aegis.identity.v1.GetUserResponse
	4,  // 11: aegis.identity.v1.IdentityService.GetUserByEmail:output_type -> aegis.identity.v1.GetUserResponse
	6,  // 12: aegis.identity.v1.IdentityService.ListProviders:output_type -> aegis.identity.v1.ListProvidersResponse
	9,  // 13: aegis.identity.v1.IdentityService.RevokeSession:output_type -> aegis.identity.v1.RevokeSessionResponse
	11, // 14: aegis.identity.v1.IdentityService.RevokeUserSessions:output_type -> aegis.identity.v1.RevokeUserSessionsResponse
	13, // 15: aegis.identity.v1.IdentityService.ListUserSessions:output_type -> aegis.identity.v1.ListUserSessionsResponse
	9,  // [9:16] is the sub-list for method output_type
	2,  // [2:9] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_identity_identity_proto_init() }
func file_proto_identity_identity_proto_init() {
	if File_proto_identity_identity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_identity_identity_proto_rawDesc), len(file_proto_identity_identity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_identity_identity_proto_goTypes,
		DependencyIndexes: file_proto_identity_identity_proto_depIdxs,
		MessageInfos:      file_proto_identity_identity_proto_msgTypes,
	}.Build()
	File_proto_identity_identity_proto = out.File
	file_proto_identity_identity_proto_goTypes = nil
	file_proto_identity_identity_proto_depIdxs = nil
}
